FROM node:10.13

USER node
ENV NODE_ENV=development
ENV PATH="/home/node/app/node_modules/.bin:${PATH}"
RUN mkdir /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node package*.json ./
RUN npm install

COPY --chown=node:node . .

CMD ["npm", "test"]
